import localFont from 'next/font/local'
import "./globals.css"
import Navbar from "./components/layout/navigation/Navbar"
import { ViewTransitions } from "next-view-transitions"
import CustomCursor from './components/layout/utils/CustomCursor'
import Footer from './components/layout/Footer'

const montserrat = localFont({
  src: [
    {
      path: './styles/fonts/montserrat-v29-latin-100.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-200.woff2',
      weight: '200',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-300.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-500.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-600.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-700.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-800.woff2',
      weight: '800',
      style: 'normal'
    },
    {
      path: './styles/fonts/montserrat-v29-latin-900.woff2',
      weight: '900',
      style: 'normal'
    }
  ],
  display: 'swap',
  // Optional: Erzeugt eine CSS-Variable, die du in deinem CSS (z. B. via @apply) nutzen kannst
  variable: '--font-montserrat'
})

const pseudoData = {
  data: [
    { attributes: { ServiceName: 'service1', DisplayName: 'Service 1' } },
    { attributes: { ServiceName: 'service2', DisplayName: 'Service 2' } },
    { attributes: { ServiceName: 'service3', DisplayName: 'Service 3' } }
  ]
}

export const metadata = {
  title: "Freisinger Metallbau",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="de">
        <body className={`antialiased ${montserrat.className}`}>
          <CustomCursor />
          <Navbar data={pseudoData}/>
            {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  )
}
